name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install libudev-dev
      run: sudo apt-get install libudev-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --verbose
    - name: Run cargo-format
      run: cargo fmt -- --check

