name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - name: Install apt packages
#      uses: ryankurte/action-apt@v0.1
#      with:
#        packages: "libudev-dev"
#    - uses: actions/checkout@v2
#    - name: Build
#      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
